trigger:
  - main  # Or your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1

  - script: |
      echo "Building Docker image..."
      docker build -t your-image-name:$(Build.BuildId) .
    displayName: 'Build Docker Image'

  - script: |
      echo "Login to DockerHub"
      docker login -u $(dockerUsername) -p $(dockerPassword)

      echo "Pushing Docker image..."
      docker tag your-image-name:$(Build.BuildId) your-dockerhub-username/your-image-name:latest
      docker push your-dockerhub-username/your-image-name:latest
    displayName: 'Push to DockerHub'
